#! /bin/bash

# See if there is -n.
all="--all-namespaces"
for x in "$@"; do
    if [ "${x}" = "-n" ] || [ "${x}" = "--namespace" ]; then
        ns="--namespaced"
        unset all
        break
    fi
done

if [ -z ${OC_ALL+x} ]; then
    grep_opt="^"
else
    grep_opt="--invert-match --file $OC_ALL"
fi

oc api-resources --verbs list ${ns} -o name | \
    grep ${grep_opt} | \
    xargs -n 1 oc get --show-kind --no-headers=false --ignore-not-found ${all} ${@:1}
